version: '3'
services:
  mongo:
    image: mongo:4.4.4
    container_name: nestjs-mongo
    restart: always
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}"
    ports:
      - "27017:27017"
    volumes:
      - ./db.files/mongo-data-4.4:/data/db
    command: --wiredTigerCacheSizeGB 1.5

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: nestjs-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - "ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}"
      - "ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}"
      - "ME_CONFIG_MONGODB_SERVER=nestjs-mongo"
      - "ME_CONFIG_MONGODB_PORT=27017"