
version: '3.1'
services:
  rmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}"
    ports:
      - "15672:15672"
      - "5672:5672"
